language: java

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - sudo apt-get install -qq --force-yes mesa-utils libgl1-mesa-swx11 libgl1-mesa-swx11-dev xvfb  
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
